name: Run test-wrapper on push and PR

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
      TEST_WRAPPER_DIR: tests-wrapper
      MAIN_RUNNER: main.py
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Run tests and capture output
        id: run_tests
        run: |
          cd "${TEST_WRAPPER_DIR}"
          python "${MAIN_RUNNER}" > ../test-run-output.log 2>&1 || true
          echo "log_saved=../test-run-output.log" >> $GITHUB_OUTPUT

      - name: Extract final JSON summary from runner output
        id: extract
        run: |
          LOGFILE=../test-run-output.log
          python - <<'PY' > extracted_summary.json